<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[25]=array(0,1,1,'5LiA5bim5LiA6Lev');
$cfg_Cs[23]=array(19,1,1,'5rex5YWl5YiG5p6Q');
$cfg_Cs[22]=array(19,1,1,'5Lu75b+X5by657O75YiX');
$cfg_Cs[19]=array(0,1,1,'5oi/5Zyw5Lqn');
$cfg_Cs[17]=array(0,1,1,'5pyf6LSn');
$cfg_Cs[15]=array(0,1,1,'5aSW5rGH');
$cfg_Cs[16]=array(0,1,1,'6IKh56Wo');
$cfg_Cs[26]=array(0,1,1,'5Lit576O6LS45piT5oiY');
$cfg_Cs[27]=array(0,-8,1,'5o6o5bm/6aG1');
?>