<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"\"); ",5,85);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",96,113);
$z[1][4]=array();
$z[2]=Array("arcurl","",128,143);
$z[2][4]=array();
$z[3]=Array("title","",159,173);
$z[3][4]=array();
$z[4]=Array("pubdate","",222,268);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",293,307);
$z[5][4]=array();
$z[6]=Array("description","",340,360);
$z[6][4]=array();

?>