<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'></a>\"); ",5,131);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",142,159);
$z[1][4]=array();
$z[2]=Array("arcurl","",174,189);
$z[2][4]=array();
$z[3]=Array("title","",205,219);
$z[3][4]=array();
$z[4]=Array("pubdate","",268,314);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",339,353);
$z[5][4]=array();
$z[6]=Array("description","",386,406);
$z[6][4]=array();

?>