<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"\"); ",16,96);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",112,127);
$z[1][4]=array();
$z[2]=Array("title","",143,157);
$z[2][4]=array();
$z[3]=Array("pubdate","",219,265);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",297,311);
$z[4][4]=array();
$z[5]=Array("scores","",343,358);
$z[5][4]=array();
$z[6]=Array("description","",404,424);
$z[6][4]=array();

?>