<?php
$z[0]=Array("field","",44,72);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",74,103);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",144,172);
$z[2][4]=array();
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n      <li>\r\n       <span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span>\r\n       <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n       <p class=\"intro\"> [field:description/]... </p>\r\n      </li>\r\n      ",244,505);
$z[3][4]=array();
$z[3][4]['titlelen']="60";
$z[3][4]['row']="5";

?>