<?php
$z[0]=Array("pubdate","",19,64);
$z[0][4]=array();
$z[0][4]['function']="MyDate('m-d',@me)";
$z[1]=Array("arcurl","",89,105);
$z[1][4]=array();
$z[2]=Array("title","",107,122);
$z[2][4]=array();
$z[3]=Array("pubdate","",177,223);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",248,262);
$z[4][4]=array();
$z[5]=Array("description","",315,335);
$z[5][4]=array();

?>