<?php
$z[0]=Array("global","",149,174);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",216,365);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['row']="8";
$z[2]=Array("global","",511,543);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",729,761);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",956,988);
$z[4][4]=array();
$z[4][4]['name']="cfg_templets_skin";

?>