<?php
$z[0]=Array("global","",68,93);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",103,129);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",131,157);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",355,380);
$z[3][4]=array();
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",390,416);
$z[4][4]=array();
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",424,452);
$z[5][4]=array();
$z[5][4]['name']="cfg_indexname";
$z[6]=Array("channel","\r\n<li class=\"page_item\"><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n",470,640);
$z[6][4]=array();
$z[6][4]['type']="top";
$z[6][4]['row']="10";
$z[6][4]['currentstyle']="";

?>