<?php
$z[0]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:title/]</a></li>\r\n",161,344);
$z[0][4]=array();
$z[0][4]['flag']="";
$z[0][4]['typeid']="";
$z[0][4]['titlelen']="56";
$z[0][4]['row']="7";
$z[0][4]['orderby']="pubdate";
$z[1]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n",451,604);
$z[1][4]=array();
$z[1][4]['flag']="";
$z[1][4]['typeid']="";
$z[1][4]['titlelen']="56";
$z[1][4]['row']="10";
$z[1][4]['orderby']="click";
$z[1][4]['subday']="";

?>